# Controller Configuration File
# This YAML file consists configuration for controller.

# Controller Configuration
params:
  gain: 201.22
  bias: 22.705
  C: .5
  ref_line_width: 280
  fast_gain: 253.26
